- hosts: all
  remote_user: vagrant
  become: yes  
  #remote_user: root                
  tasks:
          - name: Ajustando o timezone do servidor
            timezone:
                    name: America/Sao_Paulo

